fx_version "cerulean"

game "gta5"

data_file 'DLC_ITYP_REQUEST' 'stream/brum_ash.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_98_special.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_98_special_lit.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_challenge.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_challenge_lit.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_kingsize.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_kingsize_lit.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_peacemaker.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_peacemaker_lit.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_queen.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_queen_lit.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_super.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_super_gold.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_joint_super_lit.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_lighter_blue.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_lighter_grey.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_lighter_red.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/clamp.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/np_farming_arch.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_checkpoint_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_chalkboards_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/0017_props_solar_batteries.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ayc_hscarecrow.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ayc_hpumpkin.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/natty_props_lollipops.ytyp'